"""Global variables to be used for the project.
"""
# GLOBAL VARIABLES
DATA_DIR = '../input/'
DATA_DIR_OUT = '../output/'
MODELS_DIR = '../models/'
CLF_DIR = '../models/clf'
RANDOM_SEED = 42
NO_CV_FOLDS = 10
LEARNING_RATE = 0.01
EPOCHS = 100
BATCH_SIZE = 10
PCA_COMPONENTS = None
CLASS_WEIGHTS = {0:0.01,
                 1:1.0}
INTENSITY_THRESHOLD = 0.01
MZ_THRESHOLD = 100
MZ_CNT_THRESHOLD = 100
CORRELATION_THRESHOLD = 0.6
NO_PEAKS_CALC = 4
